# Generated by Django 2.1.4 on 2018-12-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0004_missionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionkey',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
