# Generated by Django 2.1.4 on 2018-12-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0006_auto_20181222_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionkey',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
