# Generated by Django 2.1.4 on 2018-12-22 10:52

from django.db import migrations, models
import spiritdashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0007_auto_20181222_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionkey',
            name='key',
            field=models.CharField(default=spiritdashboard.models.generate_random_key, max_length=10, unique=True),
        ),
    ]
