# Generated by Django 2.1.4 on 2018-12-22 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0008_auto_20181222_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
