# Generated by Django 2.1.4 on 2018-12-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0009_auto_20181222_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
