# Generated by Django 2.1.4 on 2018-12-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0011_auto_20181223_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
