# Generated by Django 2.1.4 on 2018-12-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0012_remove_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
