# Generated by Django 2.1.4 on 2018-12-23 11:14

from django.db import migrations, models
import spiritdashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0013_auto_20181223_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=spiritdashboard.models.generate_profile_picture, upload_to=''),
        ),
    ]
