# Generated by Django 2.1.4 on 2018-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0015_auto_20181223_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='health_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
