# Generated by Django 2.1.7 on 2019-02-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiritdashboard', '0018_auto_20190212_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
